spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.show-sql=true
spring.jpa.defer-datasource-initialization=true

# HTTPS
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:server_1bib23398.jks
server.ssl.key-store-type=JKS
server.ssl.key-store-password=passServer1bib
server.ssl.key-alias=Server_1BIB23398