spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate ??? ???????/??????? ??????? (??????? users)
# ????? ??????? ???????? update ?? create ????????? ???????? ????? ? ??????????
spring.jpa.hibernate.ddl-auto=create

# ????????? ?????????? schema.sql, ??? ??? ?? ??????????? ? ?????? ???????
spring.sql.init.mode=never

spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=${JWT_SECRET}