# ??????????? ? ??
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ????????? Hibernate DDL
spring.jpa.hibernate.ddl-auto=none

# ???? ???????? ?????????? schema.sql ? data.sql
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# ??? JPA + SQL init (????? ???????????? Spring Boot 3+)
spring.jpa.defer-datasource-initialization=true

# ???????????: ?????????? SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true