name: Java CI with Maven and SSL (Task 6)

on:
  push:
    branches: [ "task-6", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Восстанавливаем сертификат из секрета (нужно и для сборки, и для тестов)
      - name: Decode SSL Keystore
        run: |
          echo "${{ secrets.SSL_KEYSTORE_BASE64 }}" | base64 --decode > src/main/resources/server_1bib23398.jks

      # Запускаем полную сборку с тестами
      - name: Build and Test with Maven
        run: ./mvnw clean package
        env:
          # Заглушки для переменных, чтобы основной application.properties не ругался при инициализации
          DB_URL: jdbc:h2:mem:testdb
          DB_USERNAME: sa
          DB_PASSWORD: ""

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: autoservice-v6-app
          path: target/*.jar